baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "darioplatania.github.io" # the base hostname & protocol for your site.
title: "darioplatania-blog"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/darioplatania"  #Add your github url here.
facebook: "https://www.facebook.com/dario.platania" #Add your stackoverflow url here.
instagram: "https://www.instagram.com/plataniadario/"  #Add your twitter url here.

#disqus comment
disqus:
    shortname: "test" #replace with your disqus comment short name

#google analytics
google:
    tracking-id: "" #paste your tracking id here
gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

author:
  name      : Dario Platania
  job       : Computer Engineer
  bio1       : "Web Developer"
  bio2       : "Co-Founder & Team Coordinator"
  thumb     : /images/dp.jpg
  email     : dariopl91@gmail.com
  url       :
  github    : https://github.com/darioplatania
  facebook  : https://www.facebook.com/SicilyOnRails/?fref=ts
  instagram : https://www.instagram.com/plataniadario/
